In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/results.csv")

df["date"] = pd.to_datetime(df["date"])

In [2]:
print(df.shape)

(49477, 9)

In [3]:
worldcup2026_df = df[
    (df["tournament"] == "FIFA World Cup")
    &
    (df["date"].dt.year == 2026)
].copy()

worldcup2026_df.shape

(72, 9)

In [4]:
historical_df = df[
    ~(
        (df["tournament"] == "FIFA World Cup")
        &
        (df["date"].dt.year == 2026)
    )
].copy()

historical_df.shape

(49405, 9)

In [5]:
historical_df.isnull().sum()

date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [6]:
historical_df["home_score"] = historical_df["home_score"].astype(int)
historical_df["away_score"] = historical_df["away_score"].astype(int)

In [7]:
historical_df.dtypes

date          datetime64[us]
home_team                str
away_team                str
home_score             int64
away_score             int64
tournament               str
city                     str
country                  str
neutral                 bool
dtype: object

In [8]:
print("Antes:", historical_df.shape)

historical_df = historical_df.drop_duplicates(
    subset=[
        "date",
        "home_team",
        "away_team",
        "home_score",
        "away_score"
    ]
).reset_index(drop=True)

print("Después:", historical_df.shape)

Antes: (49405, 9)
Después: (49404, 9)

In [9]:
historical_df.to_csv(
    "../data/interim/historical_matches.csv",
    index=False
)

worldcup2026_df.to_csv(
    "../data/interim/worldcup2026_matches.csv",
    index=False
)

In [10]:
historical_df.shape

(49404, 9)

In [12]:
historical_df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False

In [13]:
historical_df.columns.tolist()

['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'tournament',
 'city',
 'country',
 'neutral']

In [11]:
worldcup2026_df.shape

(72, 9)

In [18]:
worldcup2026_df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49405,2026-06-11,Mexico,South Africa,2.0,0.0,FIFA World Cup,Mexico City,Mexico,False
49406,2026-06-11,South Korea,Czech Republic,2.0,1.0,FIFA World Cup,Zapopan,Mexico,True
49407,2026-06-12,Canada,Bosnia and Herzegovina,1.0,1.0,FIFA World Cup,Toronto,Canada,False
49408,2026-06-12,United States,Paraguay,4.0,1.0,FIFA World Cup,Inglewood,United States,False
49409,2026-06-13,Qatar,Switzerland,1.0,1.0,FIFA World Cup,Santa Clara,United States,True

In [22]:
worldcup2026_df.dtypes

date          datetime64[us]
home_team                str
away_team                str
home_score           float64
away_score           float64
tournament               str
city                     str
country                  str
neutral                 bool
dtype: object

In [23]:
worldcup2026_df.isnull().sum()

date           0
home_team      0
away_team      0
home_score    44
away_score    44
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [27]:
worldcup2026_df["date"].value_counts().sort_index().sum()

np.int64(72)